# Generated by Django 4.2.1 on 2023-06-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_persona_id_persona_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo_documento',
            field=models.CharField(default='', max_length=20),
        ),
    ]
