# Generated by Django 4.2.1 on 2023-06-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_persona_tipo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='persona',
        ),
    ]
