# Generated by Django 4.2.1 on 2023-06-03 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_tarea_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='api.persona'),
        ),
    ]
